config/routes.rb
Eileenwold::Application.routes.draw do

  get "/galleries" => "galleries#index", as: 'galleries', format: false
  get "/galleries/:name" => "galleries#show", as: 'gallery', format: false

  get "/resume.php" => "pages#resume", format: false
  get "/resume" => "pages#resume", as: 'resume', format: false

  get "/artiststatement.php" => "pages#artist_statement", format: false
  get "/artist-statement" => "pages#artist_statement", as: 'artist_statement', format: false

  get "/contact.php" => "pages#contact"
  get "/contact" => "pages#contact", as: 'contact', format: false

  get "/northshoresun.php" => "pages#northshoresun", format: false
  get "/northshoresun" => "pages#northshoresun", as: 'northshoresun', format: false

  root :to => "pages#home"

end

app/models/gallery.rb
class Gallery
  include Attribution

  has_many :pictures

  integer :id
  string :name

  GALLERIES = %w[energy_studies empty_waters west_virginia squaremeter smokestacks transfers photography digitalcrops]

  def self.all
    @galleries ||= GALLERIES.map.with_index do |name, i|
      new(id: i+1,
          name: name,
          pictures: YAML.load_file(Rails.root.join("db/galleries/#{name}.yml")))
    end
  end

  def self.find(id)
    find_by(id: id)
  end

  def self.find_by(params)
    all.detect do |gallery|
      params.all? do |attr, value|
        gallery.send(attr) == value
      end
    end
  end

  def default_picture
    @default_picture ||= pictures.detect(&:default)
  end

  def title
    case name
    when 'digitalcrops' then 'Blocked Out'
    when 'photography' then 'Fueling Baltimore'
    when 'transfers' then 'Energy Infrastructure'
    when 'west_virginia' then 'West Virginia Coal'
    when 'squaremeter' then 'Square Meter'
    else name.titleize
    end
  end

  def to_param
    name
  end

  def description
    case name
    when "energy_studies" then %{How is electricity made, distributed and used? These explorations of renewable energy sources are often constructed out of recycled or found materials.  They reflect limitations of current energy practices as well as the possibility of inquisitive and inventive thought.}
    when "empty_waters" then %{Baltimore's health department warns swimming in the harbor should be avoided due to the risk of disease from bacteria. This project examines our human perception of and relationship to nature, specifically the Chesapeake Bay. As the world’s third largest estuary, the bay was once a pristine place, productive ecosystem and a leading source of U.S. food production. But after years of pollution, what was once known as the great shellfish bay has lost 70 percent of its crabs and almost 100 percent of its oysters. Formerly a thriving body of water is being sacrificed, because of our demand for cheap energy and cheap chicken.}
    when "west_virginia" then %{This project is a documentation of a six month investigation into where the supply at the Baltimore coal terminal comes from. I traveled down to the southern mountain ranges of West Virginia and documented the surface coal mines from the air and the ground. I wanted to investigate the extraction of coal from all angles through drawing, photography, video, interviews with coal miners, as well as environmentalists. I chartered a flight over active and reclaimed mines but also walked along the smallest streams that are changing because of the coal industry. Exploring this topic in both a macro an micro way, the drawings are done from specific areas of photographs to abstract our perception one step further and to see photography as a non-static art experience, to be viewed and reviewed for different information over time.}
    when "squaremeter" then %{This series notates each planetary square meter of mature, 100 year old forest that acts as the carbon sink for each gallon of oil burned. The square meter also frames the rate of deforestation that counteracts that balance. This photographic documentation of performance of placing a square meter of yellow tape in various locations, explores ideas of sustainability but also acts as a reminder of the totality of the political and social systems already in place.}
    else %{}
    end
  end
end

app/models/picture.rb
class Picture
  include Attribution

  belongs_to :gallery

  integer :id
  string :name
  string :title
  integer :year
  string :size
  string :medium
  string :info
  boolean :default

  def image_path(size)
    "/images/galleries/#{gallery.name}/#{size}/#{name}"
  end

  def caption
    "#{title}, #{year}<br />#{medium}, #{size}".html_safe
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find_by(name: params[:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<% content_for :html_head do %>
  <style type="text/css">
    .style3 {
      color: #383740;
      font-weight: bold;
    }

    .style4 {
      color: #383740;
      font-size: 16px;
    }

    .style5 {
      color: #FFFFFF
    }
  </style>
<% end %>

<table border="0" cellspacing="0" cellpadding="0" width="800" align="center">
  <tr>
    <td colspan="6" class="content" valign="top">
      <%= render "layouts/header" %>
        <table border="0" cellspacing="0" cellpadding="10" width="100%">
          <tr>
            <td valign="top" width="194">
              <div align="right"><br /></div>
              <p align="right"><a href="galleries.php">GALLERY</a></p>
              <p align="right"><a href="resume.php">RESUME</a></p>
							<p align="right"><a href="artiststatement.php">ARTIST STATEMENT</a></p>
              <p align="right"><a href="contact.php">CONTACT / PRESS</a></p>
							<p align="right"><a href="http://www.eileenwold.blogspot.com/">BLOG</a></p>
            </td>
            <td width="368" valign="top" style="padding-right: 30px">
              <div id="blog">
                <div align="center"><img src="images/galleries/smokestacks/large/smokestacknight.jpg" width="255" height="247" align="right" /></div>
              </div>
            </td>
            <td valign="top" width="200"><div id="now"><br />
              <img src="images/galleries/transfers/wide/scienceofaneweconomy.jpg" width="150" height="100" />
              <p><img src="images/galleries/transfers/wide/industrialdevelopment.jpg" width="150" height="100" /></p>
              <p>&nbsp;</p>
            </div></td>
          </tr>
        </table>
      <%= render "layouts/footer" %>

app/views/galleries/index.html.erb
<%= render "layouts/header" %>

<h2><%= link_to "Projects", galleries_path %></h2>

<table border="0" cellspacing="0" cellpadding="40" align="center">
  <% @galleries.each_with_index do |gallery, i| %>
    <% if i.zero? %>
      <tr>
    <% elsif i%4 == 0 %>
      </tr><tr>
    <% end %>
      <td align="center" valign="top" class="thumb">
        <%= link_to gallery_path(gallery.name), title: gallery.default_picture.title do %>
          <%= image_tag gallery.default_picture.image_path(:small), alt: gallery.default_picture.title, title: gallery.default_picture.title, border: 0 %>
          <br />
          <strong><%= gallery.title %></strong>
        <% end %>
      </td>
  <% end %>
    </tr>
  </table>
<%= render "layouts/footer" %>

app/views/galleries/show.html.erb
<%= render "layouts/header" %>

  <h2>
    <%= link_to "Projects", galleries_path %>
    <span style="font-size: 12p; font-weight: normal">&gt;</span>
    <%= @gallery.title %>
  </h2>

  <table border="0" cellspacing="0" cellpadding="20" align="center">
    <tr>
      <td width="50%" valign="top">
        <p style="font-weight: normal; margin-top: 0; font-size: 12px"><%= @gallery.description %></p>
      </td>
      <td width="50%" valign="top">
        <% case @gallery.name %>
        <% when "empty_waters" %>
          <div style="text-align: center">
            <iframe src="http://player.vimeo.com/video/20146296?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1&amp;loop=1" width="400" height="225" frameborder="0"></iframe>
          </div>
        <% when "west_virginia" %>
          <div style="text-align: center">
            <iframe src="http://player.vimeo.com/video/20153256?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1&amp;loop=1" width="333" height="250" frameborder="0"></iframe>
          </div>
        <% when "squaremeter" %>
          <img src="/images/square_meter_installation.jpg" width="400" alt="Square Meter Project" />
        <% when "digitalcrops" %>
          <img src="/images/galleries/digitalcrops/install.jpg" width="400" alt="Blocked Out" />
        <% end %>
      </td>
    </tr>
  </table>

  <table border="0" cellspacing="0" cellpadding="20" align="center">
    <% @gallery.pictures.each_with_index do |picture, i| %>
      <% if i.zero? %>
        <tr>
      <% elsif i%5 == 0 %>
        </tr><tr>
      <% end %>
      <td align="center" valign="top" class="thumb">
        <a title="<%= picture.caption %>" href="<%= picture.image_path(:large) %>" rel="lightbox[gallery]" >
          <%= image_tag picture.image_path(:small), alt: picture.title, title: picture.title, border: 0 %>
          <br />
          <strong><%= picture.title %></strong>
        </a>
      </td>
    <% end %>
    </tr>
  </table>
<%= render "layouts/footer" %>

app/views/layouts/_footer.html.erb
        </td>
      </tr>
      <tr>
        <td class="footer" colspan="6">
          Copyright &copy; 1997-<%= Time.current.year %>
          &nbsp;&nbsp;&nbsp;
          Eileen T. Wold
          &nbsp;&nbsp;&nbsp;
          All Rights Reserved
        </td>
      </tr>
    </table>
  </body>
</html>

app/views/layouts/_header.html.erb
<style type="text/css">
  .style6 {
    font-family: Arial, Helvetica, sans-serif;
    font-weight: bold;
  }
  .style7 {font-family: Arial, Helvetica, sans-serif}
  .style3 {	color: #383740;
    font-weight: bold;
  }
  .style4 {	color: #383740;
    font-size: 16;
  }
  .style5 {color: #FFFFFF}
</style>

<table border="0" cellspacing="0" cellpadding="0" width="800" align="center">
  <tr>
    <td colspan="2">
      <h2><span class="style6"><span class="style3"><a href="/" class="style4">E I L E E N<span class="style5">_</span>W O L D </a></span></span></h2>
    </td>
    <td colspan="4" align="right" valign="bottom">
      <h2><span class="style7"></span></h2>
    </td>
  </tr>
  <h2><span class="style6"></span></h2>
  <tr>
    <td colspan="6" valign="top"><span class="content style6"></span>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
  <head>
    <title>Eileen T. Wold</title>
    <script type="text/javascript" src="/js/prototype.js"></script>
    <script type="text/javascript" src="/js/scriptaculous.js?load=effects"></script>
    <script type="text/javascript" src="/js/lightbox.js"></script>
    <link rel="stylesheet" href="/css/style.css" type="text/css"/>
    <link rel="stylesheet" href="/css/lightbox.css" type="text/css" media="screen" />
    <%= yield :html_head %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/artist_statement.html.erb
<% content_for :html_head do %>
<style type="text/css">
  .style1 {font-size: 12px}
</style>
<% end %>

<%= render "layouts/header" %>

<p style="font-weight: normal; font-size: 12px; color: #383740">
<br />
<br />
<br />
<b>ARTIST STATEMENT</b>
<br/>
<br/>
My research and artistic practice question the political, scientific, economic, and social systems surrounding energy production through both a global and local lens.  I am interested in how these systems are intrinsically tied to the land and its development, and the contemporary condition of a planetary environmental consciousness.
<br />
<br />
Through exploration of structures that represent fossil fuel production within our landscape such as coal mines, power plants and oil refineries, I approach the issue of power production with awareness of its ecological connection.  I reach out to a variety of professionals such as economists, journalists, engineers, and scientists, to implement an interdisciplinary approach to art and with a careful eye for observation, can integrate ideas and move beyond traditional boundaries.
<br />
<br />
I use my position as an artist to create a visual conversation that challenges our inherited system of electricity creation and distribution.  I record and respond to research with art making to better understand the world as a contingent network that is fluid and changeable.
<br />
<br />
Through informal notations of DIY energy projects, studies on sustainability,  and a diverse artistic tool kit that includes photography, drawing, sculptural installation and video, I investigate the importance of abundant sustainable energy and explore what is possible  through reflection, creativity and invention.  <br />
</p>
<p><span class="style1">&nbsp;</span></p>
<p><img src="images/galleries/transfers/large/scienceofaneweconomy.jpg" width="689" height="119"></p>

<%= render "layouts/footer" %>

app/views/pages/contact.html.erb
<% content_for :html_head do %>
  <style type="text/css">
    .style1 {font-size: 11px}
    .style2 {font-size: 12px}
  </style>
<% end %>

<%= render "layouts/header" %>
<p>
<br />
<span class="style1">
  <br />
  <b>CONTACT</b>
  <br/>
  <br/>
  Eileen T. Wold<br/>
  1409 William Street <br />
  Baltimore, MD 21230<br/>
  info@eileenwold.com<br>
  <br/>
  <br/>
  <b class="header">PRESS</b>
  <br/>
  <br/>

  <b>Eye On: Eileen Wold,  </b>
  By Jill Gordon, 11/27/12
  <a href="http://www.bmoreart.com/2012/11/eye-on-eileen-wold-by-jill-gordon.html" target="_blank">Bmore Art</a>
  <br/>


  <b>Water Sonettos,  </b>
  By Baynard Woods, 5/9/12
  <a href="http://citypaper.com/arts/visualart/em-water-sonettos-em-1.1312339?pgno=2" target="_blank">Baltimore City Paper</a>
  <br/>


  <b>Eileen Wold inspires as activist artist,  </b>
  By Kim Hall,11/17/11
  <a href="http://magazine.loyola.edu/issue/alumni/2565/activist-artist" target="_blank">Loyola University Magazine</a>
  <br/>

  <b>Artist Portrays Baltimore's Degraded Harbor,  </b>
  By Timothy B. Wheeler,2/3/11
  <a href="http://www.baltimoresun.com/features/green/bs-gr-harbor-art-show-20110203,0,1324554.story" target="_blank">The Baltimore Sun</a>
  <br/>

  <b>'Empty Waters' Artist Delves Into Baltimore Harbor,  </b>
  By Libby Zay, 2/10/11
  <a href="http://www.citysbest.com/baltimore/news/2011/02/10/empty-waters-artist-delves-deep-into-baltimore-harbor/" target="_blank">www.citysbest.com</a>
  <br/>

  <b>Awareness Through Art: Eileen Wold,  </b>
  By Kate McGinley, 2/14/11
  <a href="http://www.loyolagreyhound.com/arts/awareness-through-art-eileen-wold-1.1979293" target="_blank">Loyola Greyhound</a>
  <br/>

  <b>An Artist Eyes Baltimore Harbor's Woes </b>
  <a href= "http://weblogs.baltimoresun.com/features/green/2011/02/an_artist_eyes_baltimore_harbo.html" target="_blank">B'more    Green Blog</a>
  <br />

  <b>Artist Eileen Wold,  </b>
  By Ann Wiker, Oct/Nov Issue 2010
  <a href="http://sobovoice.com/sobo_voice_baltimore_magazine/Sobo-Voice-Oct_Nov_2010.pdf" target="_blank">Sobo Voice Magazine</a>
  <br/>

  <b>The Art of Energy,  </b>
  By Elizabeth Evitts Dickinson 12/10/08
  <a href="http://www.metropolismag.com/pov/?p=3292" target="_blank">Metropolis Magazine</a>
  <br/>

  <b>The Work of Eileen Wold,  </b>
  <a href="http://urbanpalimpsest.blogspot.com/2008/12/work-of-eileen-wold.html" target="_blank">Urban Palimpsest</a>
  <br/>

  <b>Miller Place Memories Mold Wold's World,  </b>
  By Nicole Cotroneo 7/9/04
  <%= link_to "North Shore Sun Paper", northshoresun_path %>
  <br/>
</span>
<br/>
</p>

<%= render "layouts/footer" %>

app/views/pages/home.html.erb
<% content_for :html_head do %>
  <style type="text/css">
    .style3 {
      color: #383740;
      font-weight: bold;
    }

    .style4 {
      color: #383740;
      font-size: 16px;
    }

    .style5 {
      color: #FFFFFF
    }
  </style>
<% end %>

<table border="0" cellspacing="0" cellpadding="0" width="800" align="center">
  <tr>
    <td colspan="6" class="content" valign="top">
      <%= render "layouts/header" %>
        <table border="0" cellspacing="0" cellpadding="10" width="100%">
          <tr>
            <td valign="top" width="194">
              <div align="right"><br /></div>
              <p align="right"><%= link_to "PROJECTS", galleries_path %></p>
              <p align="right"><%= link_to "RESUME", resume_path %></p>
              <p align="right"><%= link_to "ARTIST STATEMENT", artist_statement_path %></p>
              <p align="right"><%= link_to "CONTACT / PRESS", contact_path %></p>
            </td>
            <td width="368" valign="top" style="padding-right: 30px">
              <div id="blog">
                <div align="center"><img src="images/galleries/empty_waters/large/empty_waters.jpg" align="right" /></div>
              </div>
            </td>
          </tr>
        </table>
      <%= render "layouts/footer" %>

app/views/pages/northshoresun.html.erb
<% content_for :html_head do %>
  <style type="text/css">
    .style1 {font-size: 12px}
  </style>
<% end %>

<%= render "layouts/header" %>
  <table border="0" cellspacing="0" cellpadding="0" width="800" align="center">
    <tr><td>
      <img src="/images/northshoresun.jpg" alt="North Shore Sun" border="0"><br/>
    </td></tr>
  </table>
<%= render "layouts/footer" %>

app/views/pages/resume.html.erb
<% content_for :html_head do %>
<style type="text/css">
  .style1 {
    font-size: 10px
  }
</style>
<% end %>

<%= render "layouts/header" %>
<p class="style1">
<b>EDUCATION</b>
<br />
<br />
<b>Maryland Institute College of Art</b> -
MFA, 2010
<br />
<b>Loyola University Maryland</b> -
BA, Visual Art, 2000
<br />
<b>Art Academy of Leuven, Belgium</b>, 1998-1999
<br />
<b>Catholic University in Leuven, Belgium</b>,  1998-1999
<br />
<br />
</p>

<p class="style1">
<b>EXHIBITIONS</b>
<br />
<br />
<b>2012</b>
<br />
<b>InFlux Gallery</b>, Water Sonettos, MD, 5/2012
<br />
<b>Slippery Rock University</b>, Green Exhibition, PA, 4/2012
<br />
<br />
<b>2011</b>
<br />
<b>University of Maryland Baltimore</b>, Solo exhibition, Empty Waters, MD, 1-4/2011
<br />
<b>California Museum of Photography</b>, Earth Through a Lens, CA, 4/2011
<br />
<b>Rancho Mirage Pubilc library</b>, Earth Through a Lens, CA, 4/2011
<br />
<b>Second Chance Warehouse</b>, Regeneration Show on Sustainability, Baltimore, MD, 4/2011
<br />
<br />
<b>2010</b>
<br />
<b>Soapbox Gallery</b>, Solo exhibition, Ambient Energy, Brooklyn, NY, 12/2010
<br />
<b>Goldman & Minton, Solo exhibition</b>, West Virginia Project, Baltimore, MD, 10/2010 - 1/2011
<br />
<b>Umbrella Arts</b>, Route 95 Artists Show, New York, NY, 7-8/ 2010
<br />
<b>Gormley Gallery</b>, College of Notre Dame of Maryland, Images from the Land, MD, 8-10/2010
<br />
<b>Conti, Fenn and Lawrence</b>, Solo exhibition, Baltimore, MD, 8-9/2010
<br />
<b>artdc Gallery</b>, Petroleum Show, Hyattsville, MD, 8/2010
<br />
<b>Pinkard Gallery</b>, MICA, Solo MFA Thesis Exhibition, Baltimore, MD 7/2010
<br />
<b>Axis Alley, Solo Art Installation</b>, Baltimore, MD, 5-7/2010
<br />
<b>Fabritory Exhibition</b>, Sustainability of North Avenue, Baltimore, MD, 4/2010
<br />
<br />
<b>2009</b>
<br />
<b>Pinkard Gallery</b>, 3rd year MFA Exhibition, MICA, Baltimore, MD, 7/2009
<br />
<b>Arts Club of Washington</b>, Solo exhibition, Washington, DC, 3/2009
<br />
<br />
<b>2008</b>
<br />
<b>Pinkard Gallery</b>, 2nd year MFA Exhibition, MICA, Baltimore, MD, 7/2008
<br />
<br />
<b>2007</b>
<br />
<b>ARTOMATIC</b>, Washington, DC,  4/2007 - 5/2007
<br />
<br />
<b>2006</b>
<br />
<b>MOCA DC</b>, Washington, DC, September Days Show,  9/2006
<br />
<b>Brickbottom Gallery</b>, Somerville, MA, Pixel Project,  7/2006 - 8/2006
<br />
<b>Three Columns Gallery</b>, Harvard University, MA, Pixel Project, 4/2006 - 5/2006
<br />
<b>Nowuno Gallery</b>, Washington, DC, 1/2006 - 3/2006
<br />
<br />
<b>2005</b>
<br />
<b>Creative Center Gallery</b>, Chelsea, New York, NY, 4x6 Show, 12/2005
<br />
<b>Art Gotham Gallery</b>, Chelsea, New York, NY, 10/2005
<br />
<b>Brooklyn Artists Gym Gallery</b>, Brooklyn, NY, 9/2005
<br />
<b>Sona Gallery</b>, Bayshore Drive Art District, Naples, FL, 8/2005 - 7/2006
<br />
<b>Montana Gallery</b>, West Yellowstone, Book Release Show, 8/2005
<br />
<b>Gallery 402</b>, Tribeca, New York, NY, The Drawing Show, 6/2005 and 9/2005
<br />
<b>Tribute Art Gallery</b>, New York, NY, StreetWise Partners Show, 4/2005
<br />
<br />
<b>2004</b>
<br />
<b>Creative Center Gallery</b>, Chelsea, New York, NY, Small Works Show, 12/2004
<br>
<b>Silver Whale Gallery</b>, NOHO, New York, NY, Group Show, 9/2004 and 9/2004
<br>
<b>The BlueSky Gallery</b>, Chelsea, New York, NY, 8/2004 - 9/2004
<br>
<b>31 Grand Gallery</b>, Brooklyn, NY, Group Show, 8/2004
<br>
<b>Gallery Two</b>, Solo Exhibiton, Port Jefferson, NY, 7/2004
<br>
<b>Dillon Scott</b>, Solo Exhibtion, New York, NY, 4 - 9/2004
<br>
<br />
<b>2000</b>
<br />
<b>Loyola University Baltimore, Humanities</b>, Senior Solo Exhibition, 4-7/2000
<br>
<b>Federal Reserve Bank of Baltimore</b>, Group Show, 1998 and 2000
<br>
<b>Loyola University Baltimore, Art Gallery</b>, Student Fine Art Show, 1998 and 2000
<br>
<br>
</p>

<p class="style1">
<br />
<b>PUBLICATIONS AND ARTICLES</b>
<br>
<br>
<b>Eileen Wold inspires as activist artist</b>, Loyola University Maryland Magazine, By Kim Hall, 11/17/11<br>
<b>'Empty Waters' Artist Delves Into Baltimore Harbor</b> Baltimore City's Best, By Libby Zay, 2/10/11<br>
<b>Artist portrays Baltimore's degraded harbor, The Baltimore Sun</b>, by Timothy B. Wheeler, 2/3/11
<br>
<b>Eileen Wold, SOBO Voice Magazine</b>, Featured artist,  by Ann Wiker, Oct/Nov 2010 issue
<br>
<b>The Art of Energy, Metropolis Magazine</b>, article by Elizabeth Evitts Dickinson, 12/2008
<br>
<b>Artists-In-Residence, The Creative Center Approach to Arts in Healthcare</b>, featured Artist-in-Residence, 2006
<br>
<b>Washington Post</b>, Home Section, Art Class Featured, 5/2006
<br>
<b>Parks Portrayed in Pen and Paint</b>, featuring three original works, published 8/2005
<br>
<b>Dogwood Journal</b>, featured artist in April/May issue, 4/2005
<br>
<b>The North Shore Sun</b> Cover Story of Weekend Section, 7/2004
</b>
 <br />
  <br />
 </p>

<p class="style1">
<b>TEACHING & OUTREACH</b>
<br>
<br>
<b>Climate Change and Sustainability Professor, MICA, Baltimore, MD</b>, Fall 2012<br>
<b>Panelist on Mountain Top Removal, College of Notre Dame of Maryland, Baltimore, MD</b>, 4/2012<br>
<b>Color Theory and 2D Design, Anne Arundel Community College, MD</b>, Fall 2010 and Spring 2011<br>
<b>Climate Change and Sustainability, MICA, Baltimore, MD</b>, Fall 2009 and Spring 2010<br>
<b>Elements of Visual Thinking, MICA, Baltimore, MD</b>, Fall2008 and Spring 2009<br>
<b>Sculptural Forms, MICA, Baltimore, MD</b>, Spring 2008<br>
<b>Watercolor Instructor, Lane Recovery Clinic, Baltimore, MD</b>, Fall 2007<br>
<b>Art instructor, The Kreeger Museum, Washington, DC</b>, 2006 - 2011<br>
<b>Architecture, landscape and drawing instructor at First Class, Washington, DC </b>, 2006 - 2007<br>
<b>Art History and Studio Art instructor, Creative Center for Arts in Healthcare, NY, NY</b>, 2004-2007<br>
<b>Artist-in-Residence, Terence Cardinal Cooke Hospital, NY, NY</b>, 2005<br>
<b>Children's National Medical Center</b>, lead artist and speaker at dedication ceremony, DC, 2003<br>
<b>Loyola University Artist Survival Classes</b>, guest lecturer, Baltimore, MD 2002 and 2003<br>
<b>Maryland Public School</b>, guest lecturer on African Art, 2002<br>
</p>

<p class="style1">
 <br />
<b>AWARDS</b> <br>  <br>

<b>Graduate Student Leadership Award, Maryland Institute College of Art </b>, Graduate Studies, 2010
<br>
<b>Loyola University Undergraduate Student Research and Scholarship Colloquium</b>, Art History research, 4/2000
<br>
<b>Loyola University Studio Art Award for Class of 2000</b>, 1998 and 1999
<br>
<b>Who's Who Students in American Universities and Colleges</b>, 1996-1997
<br>
</p>
<span class="style1"><br>


</p>
    </span>

<%= render "layouts/footer" %>